---
title: "1-1-line"
author: "Yingfei Jiang"
date: "3/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(patchwork)
library(paletteer)

#a color blind palette I found online

cbPalette_full <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

cbbPalette <- c("#2D8E87", "#FEBC38", "#85C0F9")

#F0E442

#a color blind palette that is different

#our palette

ww_palette_4 <- c("#C84900", "#4B8FF7FF", "#2A363BFF","#99B898FF")
```

```{r}
raw_df <- read_csv("calculation_result.csv") %>% 
  clean_names()

baseline_gwp <- raw_df %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    type == "Substitution" ~ substituion_type
  )) %>% 
  select(ghg, feedstock, type_final) %>% 
  spread(key = type_final, value = ghg) %>% 
  clean_names()

ggplot(baseline_gwp)+
  geom_point(aes(x = economic, y = n_fertilizer, color = feedstock, shape = "N Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = k_fertilizer, color = feedstock, shape = "K Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = biofuel, color = feedstock, shape = "Biofuel"), size = 3)+
  geom_point(aes(x = economic, y = animal_feed, color = feedstock, shape = "Animal Feed"), size = 3)+
  geom_point(aes(x = economic, y = x2nd_oil, color = feedstock, shape = "2nd Oil"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
  xlim(0, 0.2)+
  ylim(0, 0.65)+
  theme_minimal()+
  #scale_color_paletteer_d("awtools::a_palette")+
  scale_color_manual(breaks = c("Cocoa","Coffee","Grape", "Olive"), values = ww_palette_4)+
  labs(x = "Economic", y = "Subsitution", color = "Feedstock", shape = "Alternate Use")

ggsave("1_1_gwp.png")
```

```{r}
baseline_ap <- raw_df %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    type == "Substitution" ~ substituion_type
  )) %>% 
  select(ap, feedstock, type_final) %>% 
  spread(key = type_final, value = ap) %>% 
  clean_names()

ggplot(baseline_ap)+
  geom_point(aes(x = economic, y = n_fertilizer, shape = feedstock, color = "N Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = k_fertilizer, shape = feedstock, color = "K Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = biofuel, shape = feedstock, color = "Biofuel"), size = 3)+
  geom_point(aes(x = economic, y = animal_feed, shape = feedstock, color = "Animal Feed"), size = 3)+
  geom_point(aes(x = economic, y = x2nd_oil, shape = feedstock, color = "2nd Oil"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
  xlim(0, 0.2)+
  ylim(0, 0.65)+
  theme_minimal()
```

```{r}
baseline_ep <- raw_df %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    type == "Substitution" ~ substituion_type
  )) %>% 
  select(ep, feedstock, type_final) %>% 
  spread(key = type_final, value = ep) %>% 
  clean_names()

ggplot(baseline_ep)+
  geom_point(aes(x = economic, y = n_fertilizer, shape = feedstock, color = "N Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = k_fertilizer, shape = feedstock, color = "K Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = biofuel, shape = feedstock, color = "Biofuel"), size = 3)+
  geom_point(aes(x = economic, y = animal_feed, shape = feedstock, color = "Animal Feed"), size = 3)+
  geom_point(aes(x = economic, y = x2nd_oil, shape = feedstock, color = "2nd Oil"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
  xlim(0, 0.2)+
  ylim(0, 0.65)+
  theme_minimal()
```
```{r}
baseline_lu <- raw_df %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    type == "Substitution" ~ substituion_type
  )) %>% 
  select(land_use, feedstock, type_final) %>% 
  spread(key = type_final, value = land_use) %>% 
  clean_names()

ggplot(baseline_lu)+
  geom_point(aes(x = economic, y = n_fertilizer, shape = feedstock, color = "N Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = k_fertilizer, shape = feedstock, color = "K Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = biofuel, shape = feedstock, color = "Biofuel"), size = 3)+
  geom_point(aes(x = economic, y = animal_feed, shape = feedstock, color = "Animal Feed"), size = 3)+
  geom_point(aes(x = economic, y = x2nd_oil, shape = feedstock, color = "2nd Oil"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
  xlim(0, 0.2)+
  ylim(0, 0.65)+
  theme_minimal()
```


```{r}
raw_df <- read_csv("calculation_result.csv") %>% 
  clean_names()

baseline_gwp <- raw_df %>% 
  replace_na(list(substituion_type = "na")) %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  filter(substituion_type != "K Fertilizer") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    str_detect(substituion_type, "Fertilizer") ~ "Substitution (Fertilizer)",
    TRUE ~ "Substitution (Others)"
  )) %>% 
  select(ghg, feedstock, type_final) %>% 
  spread(key = type_final, value = ghg) %>% 
  clean_names()

ggplot(baseline_gwp)+
  geom_point(aes(x = economic, y = substitution_fertilizer, color = feedstock, shape = "Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = substitution_others, color = feedstock, shape = "Others"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
  xlim(0, 0.2)+
  ylim(0, 0.65)+
  theme_minimal()+
  xlab(expression(paste("GWP under Economic Allocation" , " (kg-CO"[2], " equivalent) ")))+
  ylab(expression(paste("GWP under Substitution" , " (kg-CO"[2], " equivalent) ")))+
  scale_color_manual(breaks = c("Cocoa","Coffee","Grape", "Olive"), values = ww_palette_4)+
  labs(color = "Feedstock", shape = "Alternate Use")

ggsave("gwp1-1.png")
```

```{r}
raw_df <- read_csv("calculation_result.csv") %>% 
  clean_names()

baseline_ap <- raw_df %>% 
  replace_na(list(substituion_type = "na")) %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  filter(substituion_type != "K Fertilizer") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    str_detect(substituion_type, "Fertilizer") ~ "Substitution (Fertilizer)",
    TRUE ~ "Substitution (Others)"
  )) %>% 
  select(ap, feedstock, type_final) %>% 
  spread(key = type_final, value = ap) %>% 
  clean_names()

ggplot(baseline_ap)+
  geom_point(aes(x = economic, y = substitution_fertilizer, color = feedstock, shape = "Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = substitution_others, color = feedstock, shape = "Others"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
#  xlim(0, 0.2)+
#  ylim(0, 0.65)+
  theme_minimal()+
  xlab(expression(paste("AP under Economic Allocation" , " (kg-SO"[2], " equivalent) ")))+
  ylab(expression(paste("AP under Substitution" , " (kg-SO"[2], " equivalent) ")))+
  scale_color_manual(breaks = c("Cocoa","Coffee","Grape", "Olive"), values = ww_palette_4)+
  labs(color = "Feedstock", shape = "Alternate Use")

ggsave("ap1-1.png")
```
```{r}
raw_df <- read_csv("calculation_result.csv") %>% 
  clean_names()

baseline_ep <- raw_df %>% 
  replace_na(list(substituion_type = "na")) %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  filter(substituion_type != "K Fertilizer") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    str_detect(substituion_type, "Fertilizer") ~ "Substitution (Fertilizer)",
    TRUE ~ "Substitution (Others)"
  )) %>% 
  select(ep, feedstock, type_final) %>% 
  spread(key = type_final, value = ep) %>% 
  clean_names()

ggplot(baseline_ep)+
  geom_point(aes(x = economic, y = substitution_fertilizer, color = feedstock, shape = "Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = substitution_others, color = feedstock, shape = "Others"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
#  xlim(0, 0.2)+
#  ylim(0, 0.65)+
  theme_minimal()+
  xlab(expression(paste("EP under Economic Allocation" , " (kg-PO"[4], " equivalent) ")))+
  ylab(expression(paste("EP under Substitution" , " (kg-PO"[4], " equivalent) ")))+
  scale_color_manual(breaks = c("Cocoa","Coffee","Grape", "Olive"), values = ww_palette_4)+
  labs(color = "Feedstock", shape = "Alternate Use")

ggsave("ep1-1.png")
```

```{r}
raw_df <- read_csv("calculation_result.csv") %>% 
  clean_names()

baseline_lu <- raw_df %>% 
  replace_na(list(substituion_type = "na")) %>% 
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  filter(substituion_type != "K Fertilizer") %>% 
  mutate(type_final = case_when(
    type == "Economic" ~ "Economic",
    str_detect(substituion_type, "Fertilizer") ~ "Substitution (Fertilizer)",
    TRUE ~ "Substitution (Others)"
  )) %>% 
  select(land_use, feedstock, type_final) %>% 
  spread(key = type_final, value = land_use) %>% 
  clean_names()

ggplot(baseline_lu)+
  geom_point(aes(x = economic, y = substitution_fertilizer, color = feedstock, shape = "Fertilizer"), size = 3)+
  geom_point(aes(x = economic, y = substitution_others, color = feedstock, shape = "Others"), size = 3)+
  geom_abline(slope = 1, intercept = 0)+
#  xlim(0, 0.2)+
#  ylim(0, 0.65)+
  theme_minimal()+
  xlab(expression(paste("Land use under Economic Allocation" , " (m"[2], " of arable land) ")))+
  ylab(expression(paste("Land use under Substitution" , " (m"[2], " of arable land) ")))+
  scale_color_manual(breaks = c("Cocoa","Coffee","Grape", "Olive"), values = ww_palette_4)+
  labs(color = "Feedstock", shape = "Alternate Use")

ggsave("lu1-1.png")
```