---
title: "results_graphs_brainstorm"
author: "Madeline Berger"
date: "3/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)


library(tidyverse)
library(janitor)
library(patchwork)
library(gt)
library(paletteer)

results_all <- read_csv("calculation_result_mb.csv") %>% 
  clean_names()

water_content <- read_csv("sa_water_content.csv")

#a color blind palette I found online

cbPalette_full <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

cbbPalette <- c("#b7472a", "#ccedd2", "#394a6d")

# pink:"#f67575"
#F0E442

#a color blind palette that is different

#our palette

ww_palette <- c("#ccedd2", "#5c94bd", "#394a6d")

```

###Making graphs for baseline results

##Baseline results
```{r}
#GHG
baseline_ghg <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  select(feedstock, ghg, type_detail)

bar_baseline_ghg <- ggplot(baseline_ghg, aes(x = feedstock, y = ghg, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Global~Warming~Potential~(kg-CO^2~equivalent)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"),values = cbbPalette)+
  guides(fill = FALSE)

bar_baseline_ghg

ggsave("bar_baseline_ghg.png")

#AP

baseline_ap <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  select(feedstock, ap, type_detail)

bar_baseline_ap <- ggplot(baseline_ap, aes(x = feedstock, y = ap, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Acidification~Potential~(kg-SO^2~equivalent)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"), values = cbbPalette)

bar_baseline_ap

ggsave("bar_baseline_ap.png")

#AP no olive

baseline_ap_noolive <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All" & feedstock != "Olive") %>% 
  select(feedstock, ap, type_detail)

bar_baseline_ap_noolive <- ggplot(baseline_ap_noolive, aes(x = feedstock, y = ap, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Acidification~Potential~(kg-SO^2~equivalent)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"), values = cbbPalette)

bar_baseline_ap_noolive



#EP

baseline_ep <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  select(feedstock, ep, type_detail)

bar_baseline_ep<- ggplot(baseline_ep, aes(x = feedstock, y = ep, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Eutrophication~Potential~(kg-PO^4~equivalent)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"), values = cbbPalette)+
  guides(fill = FALSE)

bar_baseline_ep

ggsave("bar_baseline_ep.png")

#EP no olive

baseline_ep_noolive <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All" & feedstock != "Olive") %>% 
  select(feedstock, ep, type_detail)

bar_baseline_ep_noolive <- ggplot(baseline_ep_noolive, aes(x = feedstock, y = ep, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Eutrophication~Potential~(kg-PO^4~equivalent)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"), values = cbbPalette)

bar_baseline_ep_noolive

#Landuse

baseline_landuse <- results_all %>%
  filter(notes == "Baseline") %>% 
  filter(feedstock != "All") %>% 
  select(feedstock, land_use, type_detail)

bar_baseline_landuse<- ggplot(baseline_landuse, aes(x = feedstock, y = land_use, group = type_detail))+ 
  geom_bar(stat = "identity", aes(fill = type_detail), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Land~Occupation~(m^2~of~arable~land)), fill = "Method")+
  scale_fill_manual(breaks = c("Economic","Substitution","Fertilizer"), values = cbbPalette)+
  scale_y_continuous(expand = c(0,0))

bar_baseline_landuse

ggsave("bar_baseline_landuse.png")
```
#Combine Graphs
```{r}

four <- (bar_baseline_ghg + bar_baseline_ap)/(bar_baseline_landuse + bar_baseline_ep)
ggsave("four_baseline.png", width = 8, height = 6)


```


#Scenario Analysis - Economic
```{r}

##

#GHG

sa_econ_ghg <- results_all %>%
  filter(type == "Economic") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, ghg, notes)

bar_saEcon_ghg <- ggplot(sa_econ_ghg, aes(x = feedstock, y = ghg, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Global~Warming~Potential~(kg-CO^2~equivalent)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)

bar_saEcon_ghg
ggsave("bar_saEcon_ghg.png", width = 8, height = 6)
```

```{r}



#AP

sa_econ_ap <- results_all %>%
  filter(type == "Economic") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, ap, notes)

bar_saEcon_ap <- ggplot(sa_econ_ap, aes(x = feedstock, y = ap, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~AP(kg-SO^2~equivalent)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)

bar_saEcon_ap



#EP

sa_econ_ep <- results_all %>%
  filter(type == "Economic") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, ep, notes)

bar_saEcon_ep <- ggplot(sa_econ_ep, aes(x = feedstock, y = ep, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~EP(kg-PO^4~equivalent)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)+
  guides(fill = FALSE)

bar_saEcon_ep


#combine ap and ep 

ap_ep_combo <- bar_saEcon_ap/bar_saEcon_ep
ggsave("ap_ep_combo.png", width = 8, height = 6)

#AP and EP but coffee / cocoa only 

sa_econ_ap_coff <- results_all %>%
  filter(type == "Economic") %>% 
  filter(feedstock == "Coffee" | feedstock == "Cocoa") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, ap, notes)

bar_saEcon_ap_coff <- ggplot(sa_econ_ap_coff, aes(x = feedstock, y = ap, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~AP~(kg-SO^2~equivalent)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)

bar_saEcon_ap_coff

#EP for coffee and cocoa
sa_econ_ep_coff <- results_all %>%
  filter(type == "Economic") %>% 
  filter(feedstock == "Coffee" | feedstock == "Cocoa") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, ep, notes)

bar_saEcon_ep_coff <- ggplot(sa_econ_ep_coff, aes(x = feedstock, y = ep, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~EP~(kg-PO^4~equivalent)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)+
  guides(fill = FALSE)

bar_saEcon_ep_coff

#combine AP and EP for coffee and cocoa

bar_saEcon_ap_coff/bar_saEcon_ep_coff
ggsave("coffee_cocoa_ap_ep.png", width = 8, height = 6)

#Land Use


sa_econ_landuse <- results_all %>%
  filter(type == "Economic") %>% 
  mutate(notes = factor(notes, levels = c("High Bound","Baseline","Low Bound"))) %>% 
  select(feedstock, land_use, notes)

bar_saEcon_landuse <- ggplot(sa_econ_landuse, aes(x = feedstock, y = land_use, group = notes))+ 
  geom_bar(stat = "identity", aes(fill = notes), position = "dodge")+
  theme_minimal()+
  labs(x = "Feedstock", y = expression(~Land~Occupation~(m^2~of~arable~land)), fill = "Price Scenario")+
  scale_fill_manual(breaks = c("High Bound","Baseline","Low Bound"), values = ww_palette)

bar_saEcon_landuse
ggsave("bar_saEcon_landuse.png", width = 8, height = 6)
```

##Scenario Analysis Substitution

```{r}

#GHG 

sub_sa_ghg <- results_all %>% 
  filter(type == "Substitution") %>% 
  select(feedstock, ghg, substituion_type, type) %>% 
  filter(substituion_type != "K Fertilizer") %>% 
  filter()
  
  






```

